[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  BUILD_TARGET = "static"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "https://www.chincoteagueislandadventures.com/:splat"
  status = 301
  force = true
  [redirects.conditions]
    host = ["pony.advancedmarketing.co"]
