name: Deploy to Netlify

on:
  push:
    branches: [v2-source]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build
        env:
          BUILD_TARGET: static

      - uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir out
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 391c2e12-520a-4bf9-84ad-538a388e9f3e
